<?php

namespace PetStoreBundle\Repository;

/**
 * StoreOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
