<?php

namespace PetStoreBundle\Repository;

/**
 * StoreOrderToProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreOrderToProductRepository extends \Doctrine\ORM\EntityRepository
{
}
